STATE_CAPITALS_CONFIG = {
  data: [
    %w(Alabama Montgomery),
    %w(Alaska Juneau),
    %w(Arizona Phoenix),
    %w(Arkansas Little\ Rock),
    %w(California Sacramento),
    %w(Colorado Denver),
    %w(Connecticut Hartford),
    %w(Delaware Dover),
    %w(Florida Tallahassee),
    %w(Georgia Atlanta),
    %w(Hawaii Honolulu),
    %w(Idaho Boise),
    %w(Illinois Springfield),
    %w(Indiana Indianapolis),
    %w(Iowa Des\ Moines),
    %w(Kansas Topeka),
    %w(Kentucky Frankfort),
    %w(Louisiana Baton\ Rouge),
    %w(Maine Augusta),
    %w(Maryland Annapolis),
    %w(Massachusetts Boston),
    %w(Michigan Lansing),
    %w(Minnesota Saint\ Paul),
    %w(Mississippi Jackson),
    %w(Missouri Jefferson\ City),
    %w(Montana Helena),
    %w(Nebraska Lincoln),
    %w(Nevada Carson\ City),
    %w(New\ Hampshire Concord),
    %w(New\ Jersey Trenton),
    %w(New\ Mexico Santa\ Fe),
    %w(New\ York Albany),
    %w(North\ Carolina Raleigh),
    %w(North\ Dakota Bismarck),
    %w(Ohio Columbus),
    %w(Oklahoma Oklahoma\ City),
    %w(Oregon Salem),
    %w(Pennsylvania Harrisburg),
    %w(Rhode\ Island Providence),
    %w(South\ Carolina Columbia),
    %w(South\ Dakota Pierre),
    %w(Tennessee Nashville),
    %w(Texas Austin),
    %w(Utah Salt\ Lake\ City),
    %w(Vermont Montpelier),
    %w(Virginia Richmond),
    %w(Washington Olympia),
    %w(West\ Virginia Charleston),
    %w(Wisconsin Madison),
    %w(Wyoming Cheyenne)
  ],
  predicate: "What is the capital of",
  game_name: "Name the state capitals!"
}